import { black } from './colors';

const typography = {
  typography: {
    fontFamily: 'Noto Sans KR',
    title1: {
      fontFamily: 'Noto Sans KR',
      fontWeight: 500,
      color: black,
      fontSize: '18px',
      lineHeight: '28px',
      fontStyle: 'normal',
    },
    title2: {
      fontFamily: 'Noto Sans KR',
      fontWeight: 500,
      color: black,
      fontSize: '16px',
      lineHeight: '24px',
      fontStyle: 'normal',
    },
    reg12: {
      fontFamily: 'Noto Sans KR',
      fontWeight: 400,
      color: black,
      fontSize: '12px',
      lineHeight: '16px',
      fontStyle: 'normal',
    },
    med12: {
      fontFamily: 'Noto Sans KR',
      fontWeight: 500,
      color: black,
      fontSize: '12px',
      lineHeight: '16px',
      fontStyle: 'normal',
    },
    bol12: {
      fontFamily: 'Noto Sans KR',
      fontWeight: 700,
      color: black,
      fontSize: '12px',
      lineHeight: '16px',
      fontStyle: 'normal',
    },
    paragraph12: {
      fontFamily: 'Noto Sans KR',
      fontWeight: 400,
      color: black,
      fontSize: '12px',
      lineHeight: '18px',
      fontStyle: 'normal',
    },
    reg14: {
      fontFamily: 'Noto Sans KR',
      fontWeight: 400,
      color: black,
      fontSize: '14px',
      lineHeight: '20px',
      fontStyle: 'normal',
    },
    med14: {
      fontFamily: 'Noto Sans KR',
      fontWeight: 500,
      color: black,
      fontSize: '14px',
      lineHeight: '20px',
      fontStyle: 'normal',
    },
    bol14: {
      fontFamily: 'Noto Sans KR',
      fontWeight: 700,
      color: black,
      fontSize: '14px',
      lineHeight: '20px',
      fontStyle: 'normal',
    },
    paragraph14: {
      fontFamily: 'Noto Sans KR',
      fontWeight: 400,
      color: black,
      fontSize: '14px',
      lineHeight: '22px',
      fontStyle: 'normal',
    },
    reg16: {
      fontFamily: 'Noto Sans KR',
      fontWeight: 400,
      color: black,
      fontSize: '16px',
      lineHeight: '24px',
      fontStyle: 'normal',
    },
    med16: {
      fontFamily: 'Noto Sans KR',
      fontWeight: 500,
      color: black,
      fontSize: '16px',
      lineHeight: '24px',
      fontStyle: 'normal',
    },
    bol16: {
      fontFamily: 'Noto Sans KR',
      fontWeight: 700,
      color: black,
      fontSize: '16px',
      lineHeight: '24px',
      fontStyle: 'normal',
    },
  },
};

export default typography;
